version: "3.7"
services:
  web:
    build: .
    command: bash -c "gunicorn api.wsgi:application --timeout 120 --workers=5 --bind 0.0.0.0:8001"
    restart: always

    volumes:
      - .:/code
      - .:/media
    ports:
      - "8005:8001"
      
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    ports:
      - 5433:5432


    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}

    
    restart: unless-stopped






volumes:
  media:
  postgres_data: